<?php

/**
 * @file
 * Common module file.
 */

use Drupal\monitoring_tool_client\Service\ModuleCollectorServiceInterface;

/**
 * Implements hook_cron().
 */
function monitoring_tool_client_cron() {
  /** @var \Drupal\Core\State\StateInterface $state_api */
  $state_api = \Drupal::state();
  $request_time = \Drupal::time()->getRequestTime();
  $next_execution = $state_api->get('monitoring_tool_client.next_execution', 0);

  // @TODO Need to change the condition to morning and lunch.
  if ($request_time >= $next_execution) {
    /** @var \Drupal\monitoring_tool_client\Service\ModuleCollectorServiceInterface $collector */
    $collector = \Drupal::service('monitoring_tool_client.module_collector');
    /** @var \Drupal\Core\Config\ImmutableConfig $setting */
    $setting = \Drupal::configFactory()->get('monitoring_tool_client.settings');

    $collector->resetCache();

    if ($setting->get('use_webhook') === FALSE) {
      /** @var \Drupal\monitoring_tool_client\Service\ClientApiServiceInterface $client_api */
      $client_api = \Drupal::service('monitoring_tool_client.client_api');

      $client_api->sendModules();
    }

    $state_api->set('monitoring_tool_client.next_execution', $request_time + ModuleCollectorServiceInterface::CACHE_EXPIRE_TIME);
  }
}
